name: mongo-sharded-cluster

services:
  cfg1:
    image: mongo:8.0
    container_name: cfg1
    restart: unless-stopped
    command:
      - bash
      - -lc
      - |
        set -e
        cp /mnt-key/mongodb.key /tmp/mongodb.key
        chown 999:999 /tmp/mongodb.key
        chmod 600 /tmp/mongodb.key
        exec gosu mongodb mongod --configsvr --replSet cfgReplSet --port 27019 --bind_ip_all --dbpath /data/db --keyFile /tmp/mongodb.key --auth
    volumes:
      - cfg1_data:/data/db
      - D:/MongoDB/mongodb.key:/mnt-key/mongodb.key:ro
    ports:
      - "37191:27019"
    networks:
      - mongo-shard-net

  cfg2:
    image: mongo:8.0
    container_name: cfg2
    restart: unless-stopped
    command:
      - bash
      - -lc
      - |
        set -e
        cp /mnt-key/mongodb.key /tmp/mongodb.key
        chown 999:999 /tmp/mongodb.key
        chmod 600 /tmp/mongodb.key
        exec gosu mongodb mongod --configsvr --replSet cfgReplSet --port 27019 --bind_ip_all --dbpath /data/db --keyFile /tmp/mongodb.key --auth
    volumes:
      - cfg2_data:/data/db
      - D:/MongoDB/mongodb.key:/mnt-key/mongodb.key:ro
    ports:
      - "37192:27019"
    networks:
      - mongo-shard-net

  cfg3:
    image: mongo:8.0
    container_name: cfg3
    restart: unless-stopped
    command:
      - bash
      - -lc
      - |
        set -e
        cp /mnt-key/mongodb.key /tmp/mongodb.key
        chown 999:999 /tmp/mongodb.key
        chmod 600 /tmp/mongodb.key
        exec gosu mongodb mongod --configsvr --replSet cfgReplSet --port 27019 --bind_ip_all --dbpath /data/db --keyFile /tmp/mongodb.key --auth
    volumes:
      - cfg3_data:/data/db
      - D:/MongoDB/mongodb.key:/mnt-key/mongodb.key:ro
    ports:
      - "37193:27019"
    networks:
      - mongo-shard-net

  shard1a:
    image: mongo:8.0
    container_name: shard1a
    restart: unless-stopped
    command: ["bash","-lc","cp /mnt-key/mongodb.key /tmp/mongodb.key && chown 999:999 /tmp/mongodb.key && chmod 600 /tmp/mongodb.key && exec gosu mongodb mongod --shardsvr --replSet shard1 --port 27018 --bind_ip_all --dbpath /data/db --keyFile /tmp/mongodb.key --auth"]
    volumes:
      - shard1a_data:/data/db
      - D:/MongoDB/mongodb.key:/mnt-key/mongodb.key:ro
    ports:
      - "27211:27018"
    networks:
      - mongo-shard-net

  shard1b:
    image: mongo:8.0
    container_name: shard1b
    restart: unless-stopped
    command: ["bash","-lc","cp /mnt-key/mongodb.key /tmp/mongodb.key && chown 999:999 /tmp/mongodb.key && chmod 600 /tmp/mongodb.key && exec gosu mongodb mongod --shardsvr --replSet shard1 --port 27018 --bind_ip_all --dbpath /data/db --keyFile /tmp/mongodb.key --auth"]
    volumes:
      - shard1b_data:/data/db
      - D:/MongoDB/mongodb.key:/mnt-key/mongodb.key:ro
    ports:
      - "27212:27018"
    networks:
      - mongo-shard-net

  shard1c:
    image: mongo:8.0
    container_name: shard1c
    restart: unless-stopped
    command: ["bash","-lc","cp /mnt-key/mongodb.key /tmp/mongodb.key && chown 999:999 /tmp/mongodb.key && chmod 600 /tmp/mongodb.key && exec gosu mongodb mongod --shardsvr --replSet shard1 --port 27018 --bind_ip_all --dbpath /data/db --keyFile /tmp/mongodb.key --auth"]
    volumes:
      - shard1c_data:/data/db
      - D:/MongoDB/mongodb.key:/mnt-key/mongodb.key:ro
    ports:
      - "27213:27018"
    networks:
      - mongo-shard-net

  shard2a:
    image: mongo:8.0
    container_name: shard2a
    restart: unless-stopped
    command: ["bash","-lc","cp /mnt-key/mongodb.key /tmp/mongodb.key && chown 999:999 /tmp/mongodb.key && chmod 600 /tmp/mongodb.key && exec gosu mongodb mongod --shardsvr --replSet shard2 --port 27018 --bind_ip_all --dbpath /data/db --keyFile /tmp/mongodb.key --auth"]
    volumes:
      - shard2a_data:/data/db
      - D:/MongoDB/mongodb.key:/mnt-key/mongodb.key:ro
    ports:
      - "27221:27018"
    networks:
      - mongo-shard-net

  shard2b:
    image: mongo:8.0
    container_name: shard2b
    restart: unless-stopped
    command: ["bash","-lc","cp /mnt-key/mongodb.key /tmp/mongodb.key && chown 999:999 /tmp/mongodb.key && chmod 600 /tmp/mongodb.key && exec gosu mongodb mongod --shardsvr --replSet shard2 --port 27018 --bind_ip_all --dbpath /data/db --keyFile /tmp/mongodb.key --auth"]
    volumes:
      - shard2b_data:/data/db
      - D:/MongoDB/mongodb.key:/mnt-key/mongodb.key:ro
    ports:
      - "27222:27018"
    networks:
      - mongo-shard-net

  shard2c:
    image: mongo:8.0
    container_name: shard2c
    restart: unless-stopped
    command: ["bash","-lc","cp /mnt-key/mongodb.key /tmp/mongodb.key && chown 999:999 /tmp/mongodb.key && chmod 600 /tmp/mongodb.key && exec gosu mongodb mongod --shardsvr --replSet shard2 --port 27018 --bind_ip_all --dbpath /data/db --keyFile /tmp/mongodb.key --auth"]
    volumes:
      - shard2c_data:/data/db
      - D:/MongoDB/mongodb.key:/mnt-key/mongodb.key:ro
    ports:
      - "27223:27018"
    networks:
      - mongo-shard-net

  shard3a:
    image: mongo:8.0
    container_name: shard3a
    restart: unless-stopped
    command: ["bash","-lc","cp /mnt-key/mongodb.key /tmp/mongodb.key && chown 999:999 /tmp/mongodb.key && chmod 600 /tmp/mongodb.key && exec gosu mongodb mongod --shardsvr --replSet shard3 --port 27018 --bind_ip_all --dbpath /data/db --keyFile /tmp/mongodb.key --auth"]
    volumes:
      - shard3a_data:/data/db
      - D:/MongoDB/mongodb.key:/mnt-key/mongodb.key:ro
    ports:
      - "27231:27018"
    networks:
      - mongo-shard-net

  shard3b:
    image: mongo:8.0
    container_name: shard3b
    restart: unless-stopped
    command: ["bash","-lc","cp /mnt-key/mongodb.key /tmp/mongodb.key && chown 999:999 /tmp/mongodb.key && chmod 600 /tmp/mongodb.key && exec gosu mongodb mongod --shardsvr --replSet shard3 --port 27018 --bind_ip_all --dbpath /data/db --keyFile /tmp/mongodb.key --auth"]
    volumes:
      - shard3b_data:/data/db
      - D:/MongoDB/mongodb.key:/mnt-key/mongodb.key:ro
    ports:
      - "27232:27018"
    networks:
      - mongo-shard-net

  shard3c:
    image: mongo:8.0
    container_name: shard3c
    restart: unless-stopped
    command: ["bash","-lc","cp /mnt-key/mongodb.key /tmp/mongodb.key && chown 999:999 /tmp/mongodb.key && chmod 600 /tmp/mongodb.key && exec gosu mongodb mongod --shardsvr --replSet shard3 --port 27018 --bind_ip_all --dbpath /data/db --keyFile /tmp/mongodb.key --auth"]
    volumes:
      - shard3c_data:/data/db
      - D:/MongoDB/mongodb.key:/mnt-key/mongodb.key:ro
    ports:
      - "27233:27018"
    networks:
      - mongo-shard-net

  shard4a:
    image: mongo:8.0
    container_name: shard4a
    restart: unless-stopped
    command: ["bash","-lc","cp /mnt-key/mongodb.key /tmp/mongodb.key && chown 999:999 /tmp/mongodb.key && chmod 600 /tmp/mongodb.key && exec gosu mongodb mongod --shardsvr --replSet shard4 --port 27018 --bind_ip_all --dbpath /data/db --keyFile /tmp/mongodb.key --auth"]
    volumes:
      - shard4a_data:/data/db
      - D:/MongoDB/mongodb.key:/mnt-key/mongodb.key:ro
    ports:
      - "27241:27018"
    networks:
      - mongo-shard-net

  shard4b:
    image: mongo:8.0
    container_name: shard4b
    restart: unless-stopped
    command: ["bash","-lc","cp /mnt-key/mongodb.key /tmp/mongodb.key && chown 999:999 /tmp/mongodb.key && chmod 600 /tmp/mongodb.key && exec gosu mongodb mongod --shardsvr --replSet shard4 --port 27018 --bind_ip_all --dbpath /data/db --keyFile /tmp/mongodb.key --auth"]
    volumes:
      - shard4b_data:/data/db
      - D:/MongoDB/mongodb.key:/mnt-key/mongodb.key:ro
    ports:
      - "27242:27018"
    networks:
      - mongo-shard-net

  shard4c:
    image: mongo:8.0
    container_name: shard4c
    restart: unless-stopped
    command: ["bash","-lc","cp /mnt-key/mongodb.key /tmp/mongodb.key && chown 999:999 /tmp/mongodb.key && chmod 600 /tmp/mongodb.key && exec gosu mongodb mongod --shardsvr --replSet shard4 --port 27018 --bind_ip_all --dbpath /data/db --keyFile /tmp/mongodb.key --auth"]
    volumes:
      - shard4c_data:/data/db
      - D:/MongoDB/mongodb.key:/mnt-key/mongodb.key:ro
    ports:
      - "27243:27018"
    networks:
      - mongo-shard-net

  shard5a:
    image: mongo:8.0
    container_name: shard5a
    restart: unless-stopped
    command: ["bash","-lc","cp /mnt-key/mongodb.key /tmp/mongodb.key && chown 999:999 /tmp/mongodb.key && chmod 600 /tmp/mongodb.key && exec gosu mongodb mongod --shardsvr --replSet shard5 --port 27018 --bind_ip_all --dbpath /data/db --keyFile /tmp/mongodb.key --auth"]
    volumes:
      - shard5a_data:/data/db
      - D:/MongoDB/mongodb.key:/mnt-key/mongodb.key:ro
    ports:
      - "27251:27018"
    networks:
      - mongo-shard-net

  shard5b:
    image: mongo:8.0
    container_name: shard5b
    restart: unless-stopped
    command: ["bash","-lc","cp /mnt-key/mongodb.key /tmp/mongodb.key && chown 999:999 /tmp/mongodb.key && chmod 600 /tmp/mongodb.key && exec gosu mongodb mongod --shardsvr --replSet shard5 --port 27018 --bind_ip_all --dbpath /data/db --keyFile /tmp/mongodb.key --auth"]
    volumes:
      - shard5b_data:/data/db
      - D:/MongoDB/mongodb.key:/mnt-key/mongodb.key:ro
    ports:
      - "27252:27018"
    networks:
      - mongo-shard-net

  shard5c:
    image: mongo:8.0
    container_name: shard5c
    restart: unless-stopped
    command: ["bash","-lc","cp /mnt-key/mongodb.key /tmp/mongodb.key && chown 999:999 /tmp/mongodb.key && chmod 600 /tmp/mongodb.key && exec gosu mongodb mongod --shardsvr --replSet shard5 --port 27018 --bind_ip_all --dbpath /data/db --keyFile /tmp/mongodb.key --auth"]
    volumes:
      - shard5c_data:/data/db
      - D:/MongoDB/mongodb.key:/mnt-key/mongodb.key:ro
    ports:
      - "27253:27018"
    networks:
      - mongo-shard-net

  shard6a:
    image: mongo:8.0
    container_name: shard6a
    restart: unless-stopped
    command: ["bash","-lc","cp /mnt-key/mongodb.key /tmp/mongodb.key && chown 999:999 /tmp/mongodb.key && chmod 600 /tmp/mongodb.key && exec gosu mongodb mongod --shardsvr --replSet shard6 --port 27018 --bind_ip_all --dbpath /data/db --keyFile /tmp/mongodb.key --auth"]
    volumes:
      - shard6a_data:/data/db
      - D:/MongoDB/mongodb.key:/mnt-key/mongodb.key:ro
    ports:
      - "27261:27018"
    networks:
      - mongo-shard-net

  shard6b:
    image: mongo:8.0
    container_name: shard6b
    restart: unless-stopped
    command: ["bash","-lc","cp /mnt-key/mongodb.key /tmp/mongodb.key && chown 999:999 /tmp/mongodb.key && chmod 600 /tmp/mongodb.key && exec gosu mongodb mongod --shardsvr --replSet shard6 --port 27018 --bind_ip_all --dbpath /data/db --keyFile /tmp/mongodb.key --auth"]
    volumes:
      - shard6b_data:/data/db
      - D:/MongoDB/mongodb.key:/mnt-key/mongodb.key:ro
    ports:
      - "27262:27018"
    networks:
      - mongo-shard-net

  shard6c:
    image: mongo:8.0
    container_name: shard6c
    restart: unless-stopped
    command: ["bash","-lc","cp /mnt-key/mongodb.key /tmp/mongodb.key && chown 999:999 /tmp/mongodb.key && chmod 600 /tmp/mongodb.key && exec gosu mongodb mongod --shardsvr --replSet shard6 --port 27018 --bind_ip_all --dbpath /data/db --keyFile /tmp/mongodb.key --auth"]
    volumes:
      - shard6c_data:/data/db
      - D:/MongoDB/mongodb.key:/mnt-key/mongodb.key:ro
    ports:
      - "27263:27018"
    networks:
      - mongo-shard-net

  shard7a:
    image: mongo:8.0
    container_name: shard7a
    restart: unless-stopped
    command: ["bash","-lc","cp /mnt-key/mongodb.key /tmp/mongodb.key && chown 999:999 /tmp/mongodb.key && chmod 600 /tmp/mongodb.key && exec gosu mongodb mongod --shardsvr --replSet shard7 --port 27018 --bind_ip_all --dbpath /data/db --keyFile /tmp/mongodb.key --auth"]
    volumes:
      - shard7a_data:/data/db
      - D:/MongoDB/mongodb.key:/mnt-key/mongodb.key:ro
    ports:
      - "27271:27018"
    networks:
      - mongo-shard-net

  shard7b:
    image: mongo:8.0
    container_name: shard7b
    restart: unless-stopped
    command: ["bash","-lc","cp /mnt-key/mongodb.key /tmp/mongodb.key && chown 999:999 /tmp/mongodb.key && chmod 600 /tmp/mongodb.key && exec gosu mongodb mongod --shardsvr --replSet shard7 --port 27018 --bind_ip_all --dbpath /data/db --keyFile /tmp/mongodb.key --auth"]
    volumes:
      - shard7b_data:/data/db
      - D:/MongoDB/mongodb.key:/mnt-key/mongodb.key:ro
    ports:
      - "27272:27018"
    networks:
      - mongo-shard-net

  shard7c:
    image: mongo:8.0
    container_name: shard7c
    restart: unless-stopped
    command: ["bash","-lc","cp /mnt-key/mongodb.key /tmp/mongodb.key && chown 999:999 /tmp/mongodb.key && chmod 600 /tmp/mongodb.key && exec gosu mongodb mongod --shardsvr --replSet shard7 --port 27018 --bind_ip_all --dbpath /data/db --keyFile /tmp/mongodb.key --auth"]
    volumes:
      - shard7c_data:/data/db
      - D:/MongoDB/mongodb.key:/mnt-key/mongodb.key:ro
    ports:
      - "27273:27018"
    networks:
      - mongo-shard-net

  shard8a:
    image: mongo:8.0
    container_name: shard8a
    restart: unless-stopped
    command: ["bash","-lc","cp /mnt-key/mongodb.key /tmp/mongodb.key && chown 999:999 /tmp/mongodb.key && chmod 600 /tmp/mongodb.key && exec gosu mongodb mongod --shardsvr --replSet shard8 --port 27018 --bind_ip_all --dbpath /data/db --keyFile /tmp/mongodb.key --auth"]
    volumes:
      - shard8a_data:/data/db
      - D:/MongoDB/mongodb.key:/mnt-key/mongodb.key:ro
    ports:
      - "27281:27018"
    networks:
      - mongo-shard-net

  shard8b:
    image: mongo:8.0
    container_name: shard8b
    restart: unless-stopped
    command: ["bash","-lc","cp /mnt-key/mongodb.key /tmp/mongodb.key && chown 999:999 /tmp/mongodb.key && chmod 600 /tmp/mongodb.key && exec gosu mongodb mongod --shardsvr --replSet shard8 --port 27018 --bind_ip_all --dbpath /data/db --keyFile /tmp/mongodb.key --auth"]
    volumes:
      - shard8b_data:/data/db
      - D:/MongoDB/mongodb.key:/mnt-key/mongodb.key:ro
    ports:
      - "27282:27018"
    networks:
      - mongo-shard-net

  shard8c:
    image: mongo:8.0
    container_name: shard8c
    restart: unless-stopped
    command: ["bash","-lc","cp /mnt-key/mongodb.key /tmp/mongodb.key && chown 999:999 /tmp/mongodb.key && chmod 600 /tmp/mongodb.key && exec gosu mongodb mongod --shardsvr --replSet shard8 --port 27018 --bind_ip_all --dbpath /data/db --keyFile /tmp/mongodb.key --auth"]
    volumes:
      - shard8c_data:/data/db
      - D:/MongoDB/mongodb.key:/mnt-key/mongodb.key:ro
    ports:
      - "27283:27018"
    networks:
      - mongo-shard-net
      
  shard9a:
    image: mongo:8.0
    container_name: shard9a
    restart: unless-stopped
    command: ["bash","-lc","cp /mnt-key/mongodb.key /tmp/mongodb.key && chown 999:999 /tmp/mongodb.key && chmod 600 /tmp/mongodb.key && exec gosu mongodb mongod --shardsvr --replSet shard9 --port 27018 --bind_ip_all --dbpath /data/db --keyFile /tmp/mongodb.key --auth"]
    volumes:
      - shard9a_data:/data/db
      - D:/MongoDB/mongodb.key:/mnt-key/mongodb.key:ro
    ports:
      - "27291:27018"
    networks:
      - mongo-shard-net

  shard9b:
    image: mongo:8.0
    container_name: shard9b
    restart: unless-stopped
    command: ["bash","-lc","cp /mnt-key/mongodb.key /tmp/mongodb.key && chown 999:999 /tmp/mongodb.key && chmod 600 /tmp/mongodb.key && exec gosu mongodb mongod --shardsvr --replSet shard9 --port 27018 --bind_ip_all --dbpath /data/db --keyFile /tmp/mongodb.key --auth"]
    volumes:
      - shard9b_data:/data/db
      - D:/MongoDB/mongodb.key:/mnt-key/mongodb.key:ro
    ports:
      - "27292:27018"
    networks:
      - mongo-shard-net

  shard9c:
    image: mongo:8.0
    container_name: shard9c
    restart: unless-stopped
    command: ["bash","-lc","cp /mnt-key/mongodb.key /tmp/mongodb.key && chown 999:999 /tmp/mongodb.key && chmod 600 /tmp/mongodb.key && exec gosu mongodb mongod --shardsvr --replSet shard9 --port 27018 --bind_ip_all --dbpath /data/db --keyFile /tmp/mongodb.key --auth"]
    volumes:
      - shard9c_data:/data/db
      - D:/MongoDB/mongodb.key:/mnt-key/mongodb.key:ro
    ports:
      - "27293:27018"
    networks:
      - mongo-shard-net


  mongos:
    image: mongo:8.0
    container_name: mongos
    restart: unless-stopped
    command:
      - bash
      - -lc
      - |
        set -e
        cp /mnt-key/mongodb.key /tmp/mongodb.key
        chown 999:999 /tmp/mongodb.key
        chmod 600 /tmp/mongodb.key
        exec gosu mongodb mongos --configdb cfgReplSet/cfg1:27019,cfg2:27019,cfg3:27019 --bind_ip_all --port 27017 --keyFile /tmp/mongodb.key
    volumes:
      - D:/MongoDB/mongodb.key:/mnt-key/mongodb.key:ro
    depends_on:
      - cfg1
      - cfg2
      - cfg3
    ports:
      - "37017:27017"
    networks:
      - mongo-shard-net

  mongos2:
    image: mongo:8.0
    container_name: mongos2
    restart: unless-stopped
    command:
      - bash
      - -lc
      - |
        set -e
        cp /mnt-key/mongodb.key /tmp/mongodb.key
        chown 999:999 /tmp/mongodb.key
        chmod 600 /tmp/mongodb.key
        exec gosu mongodb mongos --configdb cfgReplSet/cfg1:27019,cfg2:27019,cfg3:27019 --bind_ip_all --port 27017 --keyFile /tmp/mongodb.key
    volumes:
      - D:/MongoDB/mongodb.key:/mnt-key/mongodb.key:ro
    depends_on:
      - cfg1
      - cfg2
      - cfg3
    ports:
      - "37018:27017"
    networks:
      - mongo-shard-net
      
  mongos3:
    image: mongo:8.0
    container_name: mongos3
    restart: unless-stopped
    command:
      - bash
      - -lc
      - |
        set -e
        cp /mnt-key/mongodb.key /tmp/mongodb.key
        chown 999:999 /tmp/mongodb.key
        chmod 600 /tmp/mongodb.key
        exec gosu mongodb mongos --configdb cfgReplSet/cfg1:27019,cfg2:27019,cfg3:27019 --bind_ip_all --port 27017 --keyFile /tmp/mongodb.key
    volumes:
      - D:/MongoDB/mongodb.key:/mnt-key/mongodb.key:ro
    depends_on:
      - cfg1
      - cfg2
      - cfg3
    ports:
      - "37019:27017"
    networks:
      - mongo-shard-net


volumes:
  cfg1_data:
  cfg2_data:
  cfg3_data:
  shard1a_data:
  shard1b_data:
  shard1c_data:
  shard2a_data:
  shard2b_data:
  shard2c_data:
  shard3a_data:
  shard3b_data:
  shard3c_data:
  shard4a_data:
  shard4b_data:
  shard4c_data:
  shard5a_data:
  shard5b_data:
  shard5c_data:
  shard6a_data:
  shard6b_data:
  shard6c_data:
  shard7a_data:
  shard7b_data:
  shard7c_data:
  shard8a_data:
  shard8b_data:
  shard8c_data:
  shard9a_data:
  shard9b_data:
  shard9c_data:

networks:
  mongo-shard-net:
    driver: bridge