name: mongo-sharded-cluster

services:
  cfg1:
    image: mongo:8.0
    container_name: cfg1
    command: >
      mongod --configsvr --replSet cfgReplSet --port 27019
      --bind_ip_all --dbpath /data/db
    volumes:
      - cfg1_data:/data/db
    ports:
      - "37191:27019"
    networks:
      - mongo-shard-net

  cfg2:
    image: mongo:8.0
    container_name: cfg2
    command: >
      mongod --configsvr --replSet cfgReplSet --port 27019
      --bind_ip_all --dbpath /data/db
    volumes:
      - cfg2_data:/data/db
    ports:
      - "37192:27019"
    networks:
      - mongo-shard-net

  cfg3:
    image: mongo:8.0
    container_name: cfg3
    command: >
      mongod --configsvr --replSet cfgReplSet --port 27019
      --bind_ip_all --dbpath /data/db
    volumes:
      - cfg3_data:/data/db
    ports:
      - "37193:27019"
    networks:
      - mongo-shard-net

  shard1a:
    image: mongo:8.0
    container_name: shard1a
    command: >
      mongod --shardsvr --replSet shard1 --port 27018
      --bind_ip_all --dbpath /data/db
    volumes:
      - shard1a_data:/data/db
    ports:
      - "27211:27018"
    networks:
      - mongo-shard-net

  shard1b:
    image: mongo:8.0
    container_name: shard1b
    command: >
      mongod --shardsvr --replSet shard1 --port 27018
      --bind_ip_all --dbpath /data/db
    volumes:
      - shard1b_data:/data/db
    ports:
      - "27212:27018"
    networks:
      - mongo-shard-net

  shard1c:
    image: mongo:8.0
    container_name: shard1c
    command: >
      mongod --shardsvr --replSet shard1 --port 27018
      --bind_ip_all --dbpath /data/db
    volumes:
      - shard1c_data:/data/db
    ports:
      - "27213:27018"
    networks:
      - mongo-shard-net

  shard2a:
    image: mongo:8.0
    container_name: shard2a
    command: >
      mongod --shardsvr --replSet shard2 --port 27018
      --bind_ip_all --dbpath /data/db
    volumes:
      - shard2a_data:/data/db
    ports:
      - "27221:27018"
    networks:
      - mongo-shard-net

  shard2b:
    image: mongo:8.0
    container_name: shard2b
    command: >
      mongod --shardsvr --replSet shard2 --port 27018
      --bind_ip_all --dbpath /data/db
    volumes:
      - shard2b_data:/data/db
    ports:
      - "27222:27018"
    networks:
      - mongo-shard-net

  shard2c:
    image: mongo:8.0
    container_name: shard2c
    command: >
      mongod --shardsvr --replSet shard2 --port 27018
      --bind_ip_all --dbpath /data/db
    volumes:
      - shard2c_data:/data/db
    ports:
      - "27223:27018"
    networks:
      - mongo-shard-net

  shard3a:
    image: mongo:8.0
    container_name: shard3a
    command: >
      mongod --shardsvr --replSet shard3 --port 27018
      --bind_ip_all --dbpath /data/db
    volumes:
      - shard3a_data:/data/db
    ports:
      - "27231:27018"
    networks:
      - mongo-shard-net

  shard3b:
    image: mongo:8.0
    container_name: shard3b
    command: >
      mongod --shardsvr --replSet shard3 --port 27018
      --bind_ip_all --dbpath /data/db
    volumes:
      - shard3b_data:/data/db
    ports:
      - "27232:27018"
    networks:
      - mongo-shard-net

  shard3c:
    image: mongo:8.0
    container_name: shard3c
    command: >
      mongod --shardsvr --replSet shard3 --port 27018
      --bind_ip_all --dbpath /data/db
    volumes:
      - shard3c_data:/data/db
    ports:
      - "27233:27018"
    networks:
      - mongo-shard-net

  shard4a:
    image: mongo:8.0
    container_name: shard4a
    command: >
      mongod --shardsvr --replSet shard4 --port 27018
      --bind_ip_all --dbpath /data/db
    volumes:
      - shard4a_data:/data/db
    ports:
      - "27241:27018"
    networks:
      - mongo-shard-net

  shard4b:
    image: mongo:8.0
    container_name: shard4b
    command: >
      mongod --shardsvr --replSet shard4 --port 27018
      --bind_ip_all --dbpath /data/db
    volumes:
      - shard4b_data:/data/db
    ports:
      - "27242:27018"
    networks:
      - mongo-shard-net

  shard4c:
    image: mongo:8.0
    container_name: shard4c
    command: >
      mongod --shardsvr --replSet shard4 --port 27018
      --bind_ip_all --dbpath /data/db
    volumes:
      - shard4c_data:/data/db
    ports:
      - "27243:27018"
    networks:
      - mongo-shard-net

  shard5a:
    image: mongo:8.0
    container_name: shard5a
    command: >
      mongod --shardsvr --replSet shard5 --port 27018
      --bind_ip_all --dbpath /data/db
    volumes:
      - shard5a_data:/data/db
    ports:
      - "27251:27018"
    networks:
      - mongo-shard-net

  shard5b:
    image: mongo:8.0
    container_name: shard5b
    command: >
      mongod --shardsvr --replSet shard5 --port 27018
      --bind_ip_all --dbpath /data/db
    volumes:
      - shard5b_data:/data/db
    ports:
      - "27252:27018"
    networks:
      - mongo-shard-net

  shard5c:
    image: mongo:8.0
    container_name: shard5c
    command: >
      mongod --shardsvr --replSet shard5 --port 27018
      --bind_ip_all --dbpath /data/db
    volumes:
      - shard5c_data:/data/db
    ports:
      - "27253:27018"
    networks:
      - mongo-shard-net

  shard6a:
    image: mongo:8.0
    container_name: shard6a
    command: >
      mongod --shardsvr --replSet shard6 --port 27018
      --bind_ip_all --dbpath /data/db
    volumes:
      - shard6a_data:/data/db
    ports:
      - "27261:27018"
    networks:
      - mongo-shard-net

  shard6b:
    image: mongo:8.0
    container_name: shard6b
    command: >
      mongod --shardsvr --replSet shard6 --port 27018
      --bind_ip_all --dbpath /data/db
    volumes:
      - shard6b_data:/data/db
    ports:
      - "27262:27018"
    networks:
      - mongo-shard-net

  shard6c:
    image: mongo:8.0
    container_name: shard6c
    command: >
      mongod --shardsvr --replSet shard6 --port 27018
      --bind_ip_all --dbpath /data/db
    volumes:
      - shard6c_data:/data/db
    ports:
      - "27263:27018"
    networks:
      - mongo-shard-net

  mongos:
    image: mongo:8.0
    container_name: mongos
    command: >
      mongos --configdb cfgReplSet/cfg1:27019,cfg2:27019,cfg3:27019
      --bind_ip_all --port 27017
    depends_on:
      - cfg1
      - cfg2
      - cfg3
      - shard1a
      - shard1b
      - shard1c
      - shard2a
      - shard2b
      - shard2c
      - shard3a
      - shard3b
      - shard3c
      - shard4a
      - shard4b
      - shard4c
      - shard5a
      - shard5b
      - shard5c
      - shard6a
      - shard6b
      - shard6c
    ports:
      - "37017:27017"
    networks:
      - mongo-shard-net

volumes:
  cfg1_data:
  cfg2_data:
  cfg3_data:
  shard1a_data:
  shard1b_data:
  shard1c_data:
  shard2a_data:
  shard2b_data:
  shard2c_data:
  shard3a_data:
  shard3b_data:
  shard3c_data:
  shard4a_data:
  shard4b_data:
  shard4c_data:
  shard5a_data:
  shard5b_data:
  shard5c_data:
  shard6a_data:
  shard6b_data:
  shard6c_data:

networks:
  mongo-shard-net:
    driver: bridge