services:
  cfg1:
    image: mongodb/mongodb-community-server:8.0-ubi8-slim
    container_name: cfg1
    command: mongod --configsvr --replSet cfgReplSet --port 27017 --dbpath /data/db
    volumes:
      - cfg1_data:/data/db
    networks:
      - mongo-shard-net

  cfg2:
    image: mongodb/mongodb-community-server:8.0-ubi8-slim
    container_name: cfg2
    command: mongod --configsvr --replSet cfgReplSet --port 27017 --dbpath /data/db
    volumes:
      - cfg2_data:/data/db
    networks:
      - mongo-shard-net

  cfg3:
    image: mongodb/mongodb-community-server:8.0-ubi8-slim
    container_name: cfg3
    command: mongod --configsvr --replSet cfgReplSet --port 27017 --dbpath /data/db
    volumes:
      - cfg3_data:/data/db
    networks:
      - mongo-shard-net

  shard1a:
    image: mongodb/mongodb-community-server:8.0-ubi8-slim
    container_name: shard1a
    command: mongod --shardsvr --replSet shard1ReplSet --port 27017 --dbpath /data/db
    volumes:
      - shard1a_data:/data/db
    networks:
      - mongo-shard-net

  shard1b:
    image: mongodb/mongodb-community-server:8.0-ubi8-slim
    container_name: shard1b
    command: mongod --shardsvr --replSet shard1ReplSet --port 27017 --dbpath /data/db
    volumes:
      - shard1b_data:/data/db
    networks:
      - mongo-shard-net

  shard1c:
    image: mongodb/mongodb-community-server:8.0-ubi8-slim
    container_name: shard1c
    command: mongod --shardsvr --replSet shard1ReplSet --port 27017 --dbpath /data/db
    volumes:
      - shard1c_data:/data/db
    networks:
      - mongo-shard-net

  shard2a:
    image: mongodb/mongodb-community-server:8.0-ubi8-slim
    container_name: shard2a
    command: mongod --shardsvr --replSet shard2ReplSet --port 27017 --dbpath /data/db
    volumes:
      - shard2a_data:/data/db
    networks:
      - mongo-shard-net

  shard2b:
    image: mongodb/mongodb-community-server:8.0-ubi8-slim
    container_name: shard2b
    command: mongod --shardsvr --replSet shard2ReplSet --port 27017 --dbpath /data/db
    volumes:
      - shard2b_data:/data/db
    networks:
      - mongo-shard-net

  shard2c:
    image: mongodb/mongodb-community-server:8.0-ubi8-slim
    container_name: shard2c
    command: mongod --shardsvr --replSet shard2ReplSet --port 27017 --dbpath /data/db
    volumes:
      - shard2c_data:/data/db
    networks:
      - mongo-shard-net

  shard3a:
    image: mongodb/mongodb-community-server:8.0-ubi8-slim
    container_name: shard3a
    command: mongod --shardsvr --replSet shard3ReplSet --port 27017 --dbpath /data/db
    volumes:
      - shard3a_data:/data/db
    networks:
      - mongo-shard-net

  shard3b:
    image: mongodb/mongodb-community-server:8.0-ubi8-slim
    container_name: shard3b
    command: mongod --shardsvr --replSet shard3ReplSet --port 27017 --dbpath /data/db
    volumes:
      - shard3b_data:/data/db
    networks:
      - mongo-shard-net

  shard3c:
    image: mongodb/mongodb-community-server:8.0-ubi8-slim
    container_name: shard3c
    command: mongod --shardsvr --replSet shard3ReplSet --port 27017 --dbpath /data/db
    volumes:
      - shard3c_data:/data/db
    networks:
      - mongo-shard-net

  shard4a:
    image: mongodb/mongodb-community-server:8.0-ubi8-slim
    container_name: shard4a
    command: mongod --shardsvr --replSet shard4ReplSet --port 27017 --dbpath /data/db
    volumes:
      - shard4a_data:/data/db
    networks:
      - mongo-shard-net

  shard4b:
    image: mongodb/mongodb-community-server:8.0-ubi8-slim
    container_name: shard4b
    command: mongod --shardsvr --replSet shard4ReplSet --port 27017 --dbpath /data/db
    volumes:
      - shard4b_data:/data/db
    networks:
      - mongo-shard-net

  shard4c:
    image: mongodb/mongodb-community-server:8.0-ubi8-slim
    container_name: shard4c
    command: mongod --shardsvr --replSet shard4ReplSet --port 27017 --dbpath /data/db
    volumes:
      - shard4c_data:/data/db
    networks:
      - mongo-shard-net

  shard5a:
    image: mongodb/mongodb-community-server:8.0-ubi8-slim
    container_name: shard5a
    command: mongod --shardsvr --replSet shard5ReplSet --port 27017 --dbpath /data/db
    volumes:
      - shard5a_data:/data/db
    networks:
      - mongo-shard-net

  shard5b:
    image: mongodb/mongodb-community-server:8.0-ubi8-slim
    container_name: shard5b
    command: mongod --shardsvr --replSet shard5ReplSet --port 27017 --dbpath /data/db
    volumes:
      - shard5b_data:/data/db
    networks:
      - mongo-shard-net

  shard5c:
    image: mongodb/mongodb-community-server:8.0-ubi8-slim
    container_name: shard5c
    command: mongod --shardsvr --replSet shard5ReplSet --port 27017 --dbpath /data/db
    volumes:
      - shard5c_data:/data/db
    networks:
      - mongo-shard-net

  shard6a:
    image: mongodb/mongodb-community-server:8.0-ubi8-slim
    container_name: shard6a
    command: mongod --shardsvr --replSet shard6ReplSet --port 27017 --dbpath /data/db
    volumes:
      - shard6a_data:/data/db
    networks:
      - mongo-shard-net

  shard6b:
    image: mongodb/mongodb-community-server:8.0-ubi8-slim
    container_name: shard6b
    command: mongod --shardsvr --replSet shard6ReplSet --port 27017 --dbpath /data/db
    volumes:
      - shard6b_data:/data/db
      - shard6b_data:/data/db
    networks:
      - mongo-shard-net

  shard6c:
    image: mongodb/mongodb-community-server:8.0-ubi8-slim
    container_name: shard6c
    command: mongod --shardsvr --replSet shard6ReplSet --port 27017 --dbpath /data/db
    volumes:
      - shard6c_data:/data/db
    networks:
      - mongo-shard-net

  mongos:
    image: mongodb/mongodb-community-server:8.0-ubi8-slim
    container_name: mongos
    command: mongos --configdb cfgReplSet/cfg1:27017,cfg2:27017,cfg3:27017 --port 27017 --bind_ip_all
    depends_on:
      - cfg1
      - cfg2
      - cfg3
      - shard1a
      - shard1b
      - shard1c
      - shard2a
      - shard2b
      - shard2c
      - shard3a
      - shard3b
      - shard3c
      - shard4a
      - shard4b
      - shard4c
      - shard5a
      - shard5b
      - shard5c
      - shard6a
      - shard6b
      - shard6c
    ports:
      - "37017:27017"
    networks:
      - mongo-shard-net

volumes:
  cfg1_data:
  cfg2_data:
  cfg3_data:
  shard1a_data:
  shard1b_data:
  shard1c_data:
  shard2a_data:
  shard2b_data:
  shard2c_data:
  shard3a_data:
  shard3b_data:
  shard3c_data:
  shard4a_data:
  shard4b_data:
  shard4c_data:
  shard5a_data:
  shard5b_data:
  shard5c_data:
  shard6a_data:
  shard6b_data:
  shard6c_data:

networks:
  mongo-shard-net:
    driver: bridge
